from exceptions.database import DriverNotSupported
from settings import DB_DATABASE, DB_HOST, DB_PORT, DB_DRIVER, DB_PASSWORD, DB_USERNAME


def load_database_connection_url():
    if DB_DRIVER == "mysql":
        return "mysql+aiomysql://{}:{}@{}:{}/{}?charset=utf8mb4".format(
            DB_USERNAME,
            DB_PASSWORD,
            DB_HOST,
            DB_PORT,
            DB_DATABASE,
        )
    elif DB_DRIVER == "sqlite":
        return "sqlite+aiosqlite:///database_persistence/{}.db".format(
            DB_DATABASE,
        )
    else:
        raise DriverNotSupported(driver=DB_DRIVER)


def load_default_database_connection_url():
    return "sqlite+aiosqlite:///database_persistence/bb_autogenerated.db"
