"""create proxy credential table

Revision ID: 36d8230cdd0b
Revises: fcd195ec3589
Create Date: 2022-03-28 14:39:24.400199

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '36d8230cdd0b'
down_revision = 'fcd195ec3589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy_credentials',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('type', sa.VARCHAR(length=255), nullable=False),
                    sa.Column('host', sa.VARCHAR(length=255), nullable=False),
                    sa.Column('port', sa.INTEGER(), nullable=False),
                    sa.Column('username', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('password', sa.TEXT(), nullable=True),
                    sa.Column('description', sa.TEXT(), nullable=True),
                    sa.Column('options', sa.TEXT(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('host', 'port', 'username')
                    )
    op.create_index(op.f('ix_proxy_credentials_type'), 'proxy_credentials', ['type'], unique=False)
    op.create_index(op.f('ix_proxy_credentials_updated_at'), 'proxy_credentials', ['updated_at'], unique=False)
    op.execute(
        "CREATE TRIGGER UpdateOnCurrentTimestamp1 "
        "AFTER UPDATE "
        "ON proxy_credentials "
        "FOR EACH ROW "
        "BEGIN "
        "update proxy_credentials set updated_at=CURRENT_TIMESTAMP WHERE id = NEW.id; "
        "END;"
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proxy_credentials_updated_at'), table_name='proxy_credentials')
    op.drop_index(op.f('ix_proxy_credentials_type'), table_name='proxy_credentials')
    op.drop_table('proxy_credentials')
    # ### end Alembic commands ###
