"""create comrade table

Revision ID: fcd195ec3589
Revises: 
Create Date: 2022-03-28 13:29:58.254746

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fcd195ec3589'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comrades',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('username', sa.VARCHAR(length=255), nullable=False),
                    sa.Column('password', sa.TEXT(), nullable=False),
                    sa.Column('description', sa.TEXT(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username')
                    )
    op.create_index(op.f('ix_comrades_updated_at'), 'comrades', ['updated_at'], unique=False)
    op.execute(
        "CREATE TRIGGER IF NOT EXISTS UpdateOnCurrentTimestamp AFTER UPDATE ON comrades "
        "BEGIN "
        "UPDATE comrades set updated_at=CURRENT_TIMESTAMP WHERE id=id; "
        "END;"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comrades_updated_at'), table_name='comrades')
    op.drop_table('comrades')
    # ### end Alembic commands ###
