"""create proxy_credentials table

Revision ID: 476e77b9725f
Revises: def0a460940e
Create Date: 2022-12-23 20:49:37.688111

"""
import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '476e77b9725f'
down_revision = 'def0a460940e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy_credentials',
                    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
                    sa.Column('type', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('protocol', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('host', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('port', mysql.MEDIUMINT(unsigned=True), nullable=False),
                    sa.Column('username', mysql.VARCHAR(length=255), nullable=True),
                    sa.Column('password', mysql.TEXT(), nullable=True),
                    sa.Column('description', mysql.TEXT(), nullable=True),
                    sa.Column('options', mysql.TEXT(), nullable=True),
                    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.Column('updated_at', mysql.TIMESTAMP(),
                              server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_proxy_credentials')),
                    sa.UniqueConstraint('host', 'port', 'username',
                                        name=op.f('uq_proxy_credentials_host_port_username'))
                    )
    with op.batch_alter_table('proxy_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proxy_credentials_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_proxy_credentials_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_proxy_credentials_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proxy_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proxy_credentials_updated_at'))
        batch_op.drop_index(batch_op.f('ix_proxy_credentials_type'))
        batch_op.drop_index(batch_op.f('ix_proxy_credentials_created_at'))

    op.drop_table('proxy_credentials')
    # ### end Alembic commands ###
