"""create comrades table

Revision ID: 922d0d31b7bb
Revises: 
Create Date: 2022-12-23 20:43:03.438845

"""
import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '922d0d31b7bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comrades',
                    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
                    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
                    sa.Column('username', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('password', mysql.TEXT(), nullable=False),
                    sa.Column('description', mysql.TEXT(), nullable=True),
                    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.Column('updated_at', mysql.TIMESTAMP(),
                              server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_comrades')),
                    sa.UniqueConstraint('username', name=op.f('uq_comrades_username'))
                    )
    with op.batch_alter_table('comrades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comrades_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comrades_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comrades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comrades_updated_at'))
        batch_op.drop_index(batch_op.f('ix_comrades_created_at'))

    op.drop_table('comrades')
    # ### end Alembic commands ###
