"""create comrades table

Revision ID: 5f966a54867e
Revises: 
Create Date: 2022-12-23 20:32:48.893733

"""
import sqlalchemy as sa
from alembic import op

from database.utils.triggers import CurrentTimestampOnUpdateTriggerDDL

# revision identifiers, used by Alembic.
revision = '5f966a54867e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comrades',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('username', sa.VARCHAR(length=255), nullable=False),
                    sa.Column('password', sa.TEXT(), nullable=False),
                    sa.Column('description', sa.TEXT(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_comrades')),
                    sa.UniqueConstraint('username', name=op.f('uq_comrades_username'))
                    )
    with op.batch_alter_table('comrades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comrades_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comrades_updated_at'), ['updated_at'], unique=False)
        batch_op.execute(str(CurrentTimestampOnUpdateTriggerDDL("comrades")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comrades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comrades_updated_at'))
        batch_op.drop_index(batch_op.f('ix_comrades_created_at'))

    op.drop_table('comrades')
    # ### end Alembic commands ###
