"""create proxy_comrades table

Revision ID: 7b2948dbb02f
Revises: 5f966a54867e
Create Date: 2022-12-23 20:33:54.360028

"""
import sqlalchemy as sa
from alembic import op

from database.utils.triggers import CurrentTimestampOnUpdateTriggerDDL

# revision identifiers, used by Alembic.
revision = '7b2948dbb02f'
down_revision = '5f966a54867e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy_comrades',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('proxy_credential_id', sa.INTEGER(), nullable=False),
                    sa.Column('comrade_id', sa.INTEGER(), nullable=False),
                    sa.Column('bandwidth_limit_b', sa.INTEGER(), server_default=sa.text('(1024)'), nullable=False),
                    sa.Column('concurrency_threads_limit', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
                    sa.Column('used_bandwidth_b', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
                    sa.Column('rotate_strategy', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
                    sa.Column('status', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_proxy_comrades'))
                    )
    with op.batch_alter_table('proxy_comrades', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_proxy_comrades_bandwidth_limit_b_proxy_comrades_concurrency_threads_limit'),
            ['bandwidth_limit_b', 'concurrency_threads_limit'], unique=False)
        batch_op.create_index(batch_op.f('ix_proxy_comrades_comrade_id'), ['comrade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proxy_comrades_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_proxy_comrades_proxy_credential_id'), ['proxy_credential_id'],
                              unique=False)
        batch_op.create_index(batch_op.f('ix_proxy_comrades_proxy_credential_id_proxy_comrades_comrade_id'),
                              ['proxy_credential_id', 'comrade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proxy_comrades_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_proxy_comrades_updated_at'), ['updated_at'], unique=False)
        batch_op.execute(str(CurrentTimestampOnUpdateTriggerDDL("proxy_comrades")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proxy_comrades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proxy_comrades_updated_at'))
        batch_op.drop_index(batch_op.f('ix_proxy_comrades_status'))
        batch_op.drop_index(batch_op.f('ix_proxy_comrades_proxy_credential_id_proxy_comrades_comrade_id'))
        batch_op.drop_index(batch_op.f('ix_proxy_comrades_proxy_credential_id'))
        batch_op.drop_index(batch_op.f('ix_proxy_comrades_created_at'))
        batch_op.drop_index(batch_op.f('ix_proxy_comrades_comrade_id'))
        batch_op.drop_index(batch_op.f('ix_proxy_comrades_bandwidth_limit_b_proxy_comrades_concurrency_threads_limit'))

    op.drop_table('proxy_comrades')
    # ### end Alembic commands ###
